pubg_init = [{'team': 'TSM', 'id': 1, 'value': 10.0, 'name': 'Viss'}, {'team': 'TSM', 'id': 2, 'value': 10.0, 'name': 'aimPR'}, {'team': 'TSM', 'id': 3, 'value': 10.0, 'name': 'SmaK'}, {'team': 'TSM', 'id': 4, 'value': 10.0, 'name': 'BreaK'}, {'team': 'Team Liquid', 'id': 5, 'value': 10.0, 'name': 'Hayz'}, {'team': 'Team Liquid', 'id': 6, 'value': 10.0, 'name': 'Scoom'}, {'team': 'Team Liquid', 'id': 7, 'value': 10.0, 'name': 'Molnman'}, {'team': 'Team Liquid', 'id': 8, 'value': 10.0, 'name': 'ollywood'}, {'team': 'Noble', 'id': 9, 'value': 10.0, 'name': 'Boom'}, {'team': 'Noble', 'id': 10, 'value': 10.0, 'name': 'Edakulous'}, {'team': 'Noble', 'id': 11, 'value': 10.0, 'name': 'TCZygote'}, {'team': 'Noble', 'id': 12, 'value': 10.0, 'name': 'Interrogate'}, {'team': 'Luminosity', 'id': 13, 'value': 10.0, 'name': 'Ninja'}, {'team': 'Luminosity', 'id': 14, 'value': 10.0, 'name': 'JP2'}, {'team': 'Luminosity', 'id': 15, 'value': 10.0, 'name': 'Drassel'}, {'team': 'Luminosity', 'id': 16, 'value': 10.0, 'name': 'Chipzy'}, {'team': 'Alliance', 'id': 17, 'value': 10.0, 'name': 'Ciggzy'}, {'team': 'Alliance', 'id': 18, 'value': 10.0, 'name': 'Odin'}, {'team': 'Alliance', 'id': 19, 'value': 10.0, 'name': 'Romz'}, {'team': 'Alliance', 'id': 20, 'value': 10.0, 'name': 'Veazyy'}, {'team': 'Cloud9', 'id': 21, 'value': 10.0, 'name': 'Moody'}, {'team': 'Cloud9', 'id': 22, 'value': 10.0, 'name': 'Frolicer'}, {'team': 'Cloud9', 'id': 23, 'value': 10.0, 'name': 'Chappie'}, {'team': 'Cloud9', 'id': 24, 'value': 10.0, 'name': 'SolidFPS'}, {'team': 'GCE', 'id': 25, 'value': 10.0, 'name': 'Fuzzface'}, {'team': 'GCE', 'id': 26, 'value': 10.0, 'name': 'mxey'}, {'team': 'GCE', 'id': 27, 'value': 10.0, 'name': 'Jembty'}, {'team': 'GCE', 'id': 28, 'value': 10.0, 'name': 'Haxete'}, {'team': 'NiP', 'id': 29, 'value': 10.0, 'name': 'Sweaterr'}, {'team': 'NiP', 'id': 30, 'value': 10.0, 'name': 'Crunch'}, {'team': 'NiP', 'id': 31, 'value': 10.0, 'name': 'Borg'}, {'team': 'NiP', 'id': 32, 'value': 10.0, 'name': 'Ekkz'}, {'team': 'Penta Sports', 'id': 33, 'value': 10.0, 'name': 'Frosz'}, {'team': 'Penta Sports', 'id': 34, 'value': 10.0, 'name': 'SIMSY'}, {'team': 'Penta Sports', 'id': 35, 'value': 10.0, 'name': 'jeemzz'}, {'team': 'Penta Sports', 'id': 36, 'value': 10.0, 'name': 'ultra'}, {'team': 'EG', 'id': 37, 'value': 10.0, 'name': 'Goul'}, {'team': 'EG', 'id': 38, 'value': 10.0, 'name': 'Pandaego'}, {'team': 'EG', 'id': 39, 'value': 10.0, 'name': 'Wattz'}, {'team': 'EG', 'id': 40, 'value': 10.0, 'name': 'gnomey'}, {'team': 'TEMPO STORM', 'id': 41, 'value': 10.0, 'name': 'Valliate'}, {'team': 'TEMPO STORM', 'id': 42, 'value': 10.0, 'name': 'YaBoiDre'}, {'team': 'TEMPO STORM', 'id': 43, 'value': 10.0, 'name': 'Meluke'}, {'team': 'TEMPO STORM', 'id': 44, 'value': 10.0, 'name': 'Sambty'}, {'team': 'METHOD GAMING', 'id': 45, 'value': 10.0, 'name': 'AndyPyro'}, {'team': 'METHOD GAMING', 'id': 46, 'value': 10.0, 'name': 'LaytoN'}, {'team': 'METHOD GAMING', 'id': 47, 'value': 10.0, 'name': 'EnergTurtle'}, {'team': 'METHOD GAMING', 'id': 48, 'value': 10.0, 'name': 'Aitzy'}, {'team': 'Crimson Esports', 'id': 49, 'value': 10.0, 'name': 'Jazza'}, {'team': 'Crimson Esports', 'id': 50, 'value': 10.0, 'name': 'TeaBone'}, {'team': 'Crimson Esports', 'id': 51, 'value': 10.0, 'name': 'MiracU'}, {'team': 'Crimson Esports', 'id': 52, 'value': 10.0, 'name': 'TEXQS'}, {'team': 'Whitekids', 'id': 53, 'value': 10.0, 'name': 'Stab'}, {'team': 'Whitekids', 'id': 54, 'value': 10.0, 'name': 'GustavQQ'}, {'team': 'Whitekids', 'id': 55, 'value': 10.0, 'name': 'Tryffeli'}, {'team': 'Whitekids', 'id': 56, 'value': 10.0, 'name': 'Wookiebookie'}, {'team': '*AAA* Gaming', 'id': 57, 'value': 10.0, 'name': 'mOnKeY'}, {'team': '*AAA* Gaming', 'id': 58, 'value': 10.0, 'name': 'oraxe'}, {'team': '*AAA* Gaming', 'id': 59, 'value': 10.0, 'name': 'Shadow1k'}, {'team': '*AAA* Gaming', 'id': 60, 'value': 10.0, 'name': 'Shiv'}, {'team': 'Team PogChamp', 'id': 61, 'value': 10.0, 'name': 'AwieN'}, {'team': 'Team PogChamp', 'id': 62, 'value': 10.0, 'name': 'EwanHC'}, {'team': 'Team PogChamp', 'id': 63, 'value': 10.0, 'name': 'FaustoCoppi'}, {'team': 'Team PogChamp', 'id': 64, 'value': 10.0, 'name': 'Jokkizz'}, {'team': 'Ghost Gaming', 'id': 65, 'value': 10.0, 'name': 'Miccoy'}, {'team': 'Ghost Gaming', 'id': 66, 'value': 10.0, 'name': 'Definelegit'}, {'team': 'Ghost Gaming', 'id': 67, 'value': 10.0, 'name': 'Austin'}, {'team': 'Ghost Gaming', 'id': 68, 'value': 10.0, 'name': 'Pr0phie'}, {'team': 'Ronin Esports', 'id': 69, 'value': 10.0, 'name': 'Duckk'}, {'team': 'Ronin Esports', 'id': 70, 'value': 10.0, 'name': 'Kraqen'}, {'team': 'Ronin Esports', 'id': 71, 'value': 10.0, 'name': 'Minifridgejr'}, {'team': 'Ronin Esports', 'id': 72, 'value': 10.0, 'name': 'notadeveloper'}, {'team': 'Miami Flamingos', 'id': 73, 'value': 10.0, 'name': 'TonyV'}, {'team': 'Miami Flamingos', 'id': 74, 'value': 10.0, 'name': 'ZeNTTRiiX'}, {'team': 'Miami Flamingos', 'id': 75, 'value': 10.0, 'name': 'DatKoko'}, {'team': 'Miami Flamingos', 'id': 76, 'value': 10.0, 'name': '1HunnaRounds'}, {'team': 'Corn Shuckers', 'id': 77, 'value': 10.0, 'name': 'Zanpah'}, {'team': 'Corn Shuckers', 'id': 78, 'value': 10.0, 'name': 'EnV'}, {'team': 'Corn Shuckers', 'id': 79, 'value': 10.0, 'name': 'PaaaRADOX'}, {'team': 'Corn Shuckers', 'id': 80, 'value': 10.0, 'name': 'eLusive'}]

pubg_beat_init = [{'team': 'TSM', 'id': 1, 'value': 10.0, 'name': 'Viss'}, {'team': 'TSM', 'id': 2, 'value': 10.0, 'name': 'aimPR'}, {'team': 'TSM', 'id': 3, 'value': 10.0, 'name': 'SmaK'}, {'team': 'TSM', 'id': 4, 'value': 10.0, 'name': 'BreaK'}, {'team': 'Noble', 'id': 9, 'value': 10.0, 'name': 'Boom'}, {'team': 'Noble', 'id': 10, 'value': 10.0, 'name': 'Edakulous'}, {'team': 'Noble', 'id': 11, 'value': 10.0, 'name': 'TCZygote'}, {'team': 'Noble', 'id': 12, 'value': 10.0, 'name': 'Interrogate'}, {'team': 'Cloud9', 'id': 21, 'value': 10.0, 'name': 'Moody'}, {'team': 'Cloud9', 'id': 22, 'value': 10.0, 'name': 'Frolicer'}, {'team': 'Cloud9', 'id': 23, 'value': 10.0, 'name': 'Chappie'}, {'team': 'Cloud9', 'id': 24, 'value': 10.0, 'name': 'SolidFPS'}, {'team': 'EG', 'id': 37, 'value': 10.0, 'name': 'Goul'}, {'team': 'EG', 'id': 38, 'value': 10.0, 'name': 'Pandaego'}, {'team': 'EG', 'id': 39, 'value': 10.0, 'name': 'Wattz'}, {'team': 'EG', 'id': 40, 'value': 10.0, 'name': 'gnomey'}, {'team': 'TEMPO STORM', 'id': 41, 'value': 10.0, 'name': 'Valliate'}, {'team': 'TEMPO STORM', 'id': 42, 'value': 10.0, 'name': 'YaBoiDre'}, {'team': 'TEMPO STORM', 'id': 43, 'value': 10.0, 'name': 'Meluke'}, {'team': 'TEMPO STORM', 'id': 44, 'value': 10.0, 'name': 'Sambty'}, {'team':'Ronin Esports', 'id': 69, 'value': 10.0, 'name': 'Duckk'}, {'team': 'Ronin Esports', 'id': 70, 'value': 10.0, 'name': 'Kraqen'}, {'team': 'Ronin Esports', 'id': 71, 'value': 10.0, 'name': 'Minifridgejr'}, {'team': 'Ronin Esports', 'id': 72, 'value': 10.0, 'name': 'notadeveloper'}, {'team':'Corn Shuckers', 'id': 77, 'value': 10.0, 'name': 'Zanpah'}, {'team': 'Corn Shuckers', 'id': 78, 'value': 10.0, 'name': 'EnV'}, {'team': 'Corn Shuckers', 'id': 79, 'value': 10.0, 'name': 'PaaaRADOX'}, {'team': 'Corn Shuckers', 'id': 80, 'value': 10.0, 'name': 'eLusive'},
                  {'team': 'Gale Force eSports', 'id': 81, 'value': 10, 'name': 'benq5'},
                  {'team': 'Gale Force eSports', 'id': 82, 'value': 10, 'name': 'Reum'},
                  {'team': 'Gale Force eSports', 'id': 83, 'value': 10, 'name': 'UnderCoverPie'},
                  {'team': 'Gale Force eSports', 'id': 84, 'value': 10, 'name': 'TheChosenZygote'},
{'team': 'Penta Sports', 'id': 33, 'value': 10.0, 'name': 'Frosz'}, {'team': 'Penta Sports', 'id': 34,      'value': 10.0, 'name': 'SIMSY'}, {'team': 'Penta Sports', 'id': 35, 'value': 10.0, 'name': 'jeemzz'}, {'team': 'Penta Sports', 'id':        36, 'value': 10.0, 'name': 'ultra'},
{'team': 'Rocket Esports', 'id': 86, 'value': 10, 'name': 'Lush'},
{'team': 'Rocket Esports', 'id': 87, 'value': 10, 'name': 'MachineGunner'},
{'team': 'Rocket Esports', 'id': 88, 'value': 10, 'name': 'Mjyoh'},
{'team': 'EnVyUs', 'id': 89, 'value': 10, 'name': 'Czechshooter'},
{'team': 'EnVyUs', 'id': 90, 'value': 10, 'name': 'Venerated'},
{'team': 'EnVyUs', 'id': 91, 'value': 10, 'name': 'Cad3n'},
{'team': 'EnVyUs', 'id': 92, 'value': 10, 'name': 'Jesselol'},
{'team': 'OpTic Gaming', 'id': 93, 'value': 10, 'name': 'Hypoc'},
{'team': 'OpTic Gaming', 'id': 94, 'value': 10, 'name': 'Bahawaka'},
{'team': 'OpTic Gaming', 'id': 95, 'value': 10, 'name': 'Teen'},
{'team': 'OpTic Gaming', 'id': 96, 'value': 10, 'name': 'Ashek'},
{'team': 'Rogue', 'id': 97, 'value': 10, 'name': 'Soltek1h'},
{'team': 'Rogue', 'id': 98, 'value': 10, 'name': 'AladdinLTD'},
{'team': 'Rogue', 'id': 99, 'value': 10, 'name': 'KronixGG'},
{'team': 'Rogue', 'id': 100, 'value': 10, 'name': 'TTfue'},
{'team': 'Check 6', 'id': 101, 'value': 10, 'name': 'Shaffer'},
{'team': 'Check 6', 'id': 102, 'value': 10, 'name': 'Durbdawg'},
{'team': 'Check 6', 'id': 103, 'value': 10, 'name': 'TheOneJ'},
{'team': 'Check 6', 'id': 104, 'value': 10, 'name': 'Acidelus'},
{'team': 'FlyQuest', 'id': 105, 'value': 10, 'name': 'Hetror'},
{'team': 'FlyQuest', 'id': 106, 'value': 10, 'name': 'Comet'},
{'team': 'FlyQuest', 'id': 107, 'value': 10, 'name': 'SomeThang'},
{'team': 'FlyQuest', 'id': 108, 'value': 10, 'name': 'Blue'},
{'team': 'Totality', 'id': 109, 'value': 10, 'name': 'Purdykurty'},
{'team': 'Totality', 'id': 110, 'value': 10, 'name': 'Nopnop'},
{'team': 'Totality', 'id': 111, 'value': 10, 'name': 'Daacannon'},
{'team': 'Totality', 'id': 112, 'value': 10, 'name': 'Smithy97'},
{'team': 'AffNity', 'id': 114, 'value': 10, 'name': 'Swifyque'},
{'team': 'AffNity', 'id': 115, 'value': 10, 'name': 'Jutzu'},
{'team': 'AffNity', 'id': 116, 'value': 10, 'name': 'Auxx'},
{'team': 'AffNity', 'id': 117, 'value': 10, 'name': 'Sehcaep'},
{'team': '4S', 'id': 118, 'value': 10, 'name': 'Poonaegy'},
{'team': '4S', 'id': 119, 'value': 10, 'name': 'Grizz'},
{'team': '4S', 'id': 120, 'value': 10, 'name': 'Trinity_Seven'},
{'team': '4S', 'id': 121, 'value': 10, 'name': 'Riftt'},
{'team': '4S', 'id': 122, 'value': 10, 'name': 'Jehee'},
{'team': 'MLGB', 'id': 123, 'value': 10, 'name': 'Biggie'},
{'team': 'MLGB', 'id': 124, 'value': 10, 'name': 'Therous'},
{'team': 'MLGB', 'id': 125, 'value': 10, 'name': 'Tunacan'},
{'team': 'MLGB', 'id': 126, 'value': 10, 'name': 'Phozhu'},
{'team': 'ShootToKill', 'id': 127, 'value': 10, 'name': 'Didz_NA'},
{'team': 'ShootToKill', 'id': 128, 'value': 10, 'name': 'Weiksworld'},
{'team': 'ShootToKill', 'id': 129, 'value': 10, 'name': 'AdamDids'},
{'team': 'ShootToKill', 'id': 130, 'value': 10, 'name': 'Lgdzxhero'},
{'team': 'ShootToKill', 'id': 131, 'value': 10, 'name': 'Uncivils'},
{'team': 'ShootToKill', 'id': 132, 'value': 10, 'name': 'Wizwiki'},
{'team': 'Set To Destroy', 'id': 133, 'value': 10, 'name': 'Painkillerr'},
{'team': 'Set To Destroy', 'id': 134, 'value': 10, 'name': 'Truhls'},
{'team': 'Set To Destroy', 'id': 135, 'value': 10, 'name': 'Benja'},
{'team': 'Set To Destroy', 'id': 136, 'value': 10, 'name': 'Raikar'},
                  ]
